### PR TITLE
bump k8s to v1.9.6

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by rimusz** [comment]
don't we run conformance tests with CI when framework changes?

**Comment by hectorj2f** [comment]
@bmcstdio Yep. Sorry @rimusz I missed some details :)

**Comment by rimusz** [comment]
gotcha

**Comment by bmcstdio** [comment]
https://github.com/cncf/k8s-conformance/pull/180

**Comment by bmcstdio** [comment]
Thanks @rimusz!

**Pull request merged**
