### PR TITLE
Upgrade to 1.7.11

### PR DESCRIPTION
**Pull request by hectorj2f**
This PR aims to upgrade our Kubernetes version to 1.7.11

### CODE REVIEW

**Comment by pires** [comment]
Assigning @spahl given we may not be releasing this after all.

**Comment by hectorj2f** [comment]
I close this PR cause we don't need it anymore. Please, open it again if you think we still need it.

**Comment by pires** [comment]
Well, we'll need a PR that installs 1.10.2 (Open) or 1.10.3 (if EE is applicable).

**Comment by hectorj2f** [comment]
I tackle it in this PR https://github.com/mesosphere/dcos-kubernetes-quickstart/pull/45

**Pull request closed without merging**
