### PR TITLE
Added minor improvements to the code and installation process

### PR DESCRIPTION
**Pull request by hectorj2f**
- Added .gitignore file
- Modified Dockerfile to fetch the latest docs-launch binary instead of compiling the source code
- Added LICENSE file
- Relocated assets inside docs folder 
- Added deploy target to Makefile to simplify the installation process
     - This requires to enable the widget in teamcity https://teamcity.mesosphere.io/admin/editBuild.html?id=buildType:ClosedSource_KubernetesAws_PrTest
- Modified README including a card to report the state of the master tests. Added a link to the examples folder and adapted the installation steps
- Reduced image size by using CentOS
ping @spahl

### CODE REVIEW

**Comment by spahl** [comment]
This is getting big. All looks good to me. We should merge and do more small ones.

@smugcloud are you good with those changes?

**Comment by pires** [comment]
Why did we add a link to TC? The framework is not (yet?) OSS and IIRC TC is privately accessed.

**Comment by hectorj2f** [comment]
@pires The purpose was clear to me. To show to people, the state of the code that they will execute. We now have specific tests for the Open code, so it makes more sense. We don't have tests in quickstart.

**Comment by pires** [comment]
This is misleading as the community only has access to our releases and not our branches (or code) or even TC. If we tell the community our builds fail, what exactly will that mean to them when they can't run our master or any other branch? From my pov, nothing meaningful and it may even mislead them into not running it because it may show as _failing_.

**Pull request merged**
